### ISSUE TITLE
computed properties

### ISSUE THREAD

**Issue by devmondo** [wiresjs/async-watch#3]
Hi again, 

i tried the following but it does not work 

```
export class Computed {
    a = 1;
    b = 2;
    c = this.a + this.b;

    constructor() {
        AsyncWatch(this, `c`, function (newVal, oldVal) {
            console.log(`Computed works`, newVal, oldVal);
        })
    }
}

let computedInstance = new Computed();
computedInstance.a = 4;
```

**Comment by nchanged** [comment]
Hm, but you are not modifying "c". You change "a", which is not watched.

**Comment by devmondo** [comment]
sorry for not explaining well, 

that is the point of computed properties, which is if you modify dependencies the target will automatically get updated.

something similar [computed in angular](http://angular-tips.com/blog/2014/02/computer-properties-with-javascript-properties/)

**Comment by nchanged** [comment]
Oh i see, it's not implemented here. However, i am working on a project (it's in a very very very early stage), which has a pretty neat module,  that combines AngularExpressions and AsyncWatch, [here](https://github.com/wiresjs/wires.js/blob/wires3/src/wires/expressions/StringInterpolation.js#L7).

I could put it into a different repository, cuz it's real handy:

```
let scope = {firstName : "Bob", lastName : "Marley"}
var model = parser.compile('Hello {{firstName}} {{lastName}}!');
model(scope, function(str){
   // Hello Bob Marley!
   // Got triggered on any modification of any dependencies and gives a compiled string
})
```

In a nutshell, this module extracts variables, automatically assigns watchers and evaluates the expression using AngularExpression (which is a tiny lib - extracted from angular by very nice people)

If you are interested, we could combine powers, just saying ;-)

**Comment by devmondo** [comment]
great work there man, 

if it could be put in dedicated repo it would be great, as people wants specific functionality and dont want to load full lib for small case.

yes i am familiar with `AngularExpression` great lib, but the project i am working on does not agree with Angular syntax :(

by the way did you hear of [jsep](https://github.com/soney/jsep) i think it gives you more control over parsing.

how we can combine powers :) ?

**Comment by nchanged** [comment]
Yeah, i heard of jsep. I tried it, but it does not really work for me

`!a.foo && !a.bar` Would fail if "a" is not defined. (if you use esprima or anything else to evaluate) AngularExpressions handles it pretty nicely and returns "true". Plus it can understand if statements.

It's not `Angular syntax` per se, it's just javascript, you can surround expressions with any symbols you like: e.g {% firstName %}. So in this case, angularExpressions just evaluate your code.

Well, if you interested in developing a mind blowing universal framework, for example ;-)

**Comment by devmondo** [comment]
man, i never knew about that ! it fails with simple thing like that, that is bad... kudo for `AngularExpression` team, i will reevaluate it again, thanks for the tip!

**Comment by nchanged** [comment]
Sure, let's chat:
skype: nchanged

**Comment by nchanged** [comment]
Implemented
https://github.com/wiresjs/async-watch/commit/d5a52b71f15a249f82a1e6699f8bd7de1281982e
